require: rubocop-rails
AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - vendor/**/*
    - app/controllers/letsencrypt_controller.rb
Rails:
  Enabled: true
Rails/HttpPositionalArguments:
  Enabled: false # This cop only applies to Rails 5
Rails/ApplicationRecord:
  Enabled: false # This cop only applies to Rails 5
Rails/HasManyOrHasOneDependent:
  Enabled: false
Layout/LineLength:
  Max: 83
  IgnoredPatterns: ['\s*#']
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 60
Metrics/BlockLength:
  Max: 60
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
